apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: techakademi
  namespace: default
spec:
  secretName: techakademi-tls-production
  dnsNames:
    - www.techakademi.com
  issuerRef:
    name: techakademi-production
    kind: ClusterIssuer