apiVersion: apps/v1
kind: Deployment
metadata:
  name: whoami-deploymenti
spec:
  replicas: 2
  selector:
    matchLabels:
      app: whoami-deploymenti
  template:
    metadata:
      labels:
        app: whoami-deploymenti
    spec:
      containers:
      - name: whoami-konteyneri
        image: containous/whoami
---
apiVersion: v1
kind: Service
metadata:
  name: whoami-servisi
  labels:
    app: whoami-deploymenti
spec:
  type: LoadBalancer
  selector:
    app: whoami-deploymenti
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP
---
apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: whoami-https-yonlendir
spec:
  redirectScheme:
    scheme: https
    permanent: true
---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: whoami-ingress-http
  namespace: default
spec:
  entryPoints:
    - web
  routes:
    - match: Host(`whoami.techakademi.com`)
      kind: Rule
      middlewares:
        - name: whoami-https-yonlendir
      services:
        - name: whoami-servisi
          port: 80
---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: whoami-ingress-https
  namespace: default
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`whoami.techakademi.com`)
      kind: Rule
      services:
        - name: whoami-servisi
          port: 80
  tls:
    secretName: whoami-tls-production
        
        
        
        