apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: merhaba-dunya
  namespace: default
spec:
  secretName: merhaba-dunya-tls-production
  dnsNames:
    - merhaba.techakademi.com
  issuerRef:
    name: merhaba-production
    kind: ClusterIssuer