apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: whoami-staging
  namespace: default
spec:
  acme:
    server: https://acme-staging-v02.api.letsencrypt.org/directory
    email: techakademi@gmail.com
    privateKeySecretRef:
      name: whoami-staging
    solvers:
    - selector: {}
      http01:
        ingress:
          class: traefik